LIBS = -lzmq -lboost_thread-mt -ltbb -lboost_program_options-mt -lboost_serialization -ltcmalloc_minimal -lrt

all: Makefile string_vector_test.cpp
	g++ string_vector_test.cpp $(LIBS) -o string_vector_test -g -O3


